### ISSUE TITLE
unable to load a file on LPC802 board over SWD

### ISSUE THREAD

**Issue by 0x72D0** [blacksphere/blackmagic#884]
I tried the following on the LPCXpresso 802 OM40000 Rev A dev board from NXP. For the BlackMagicProbe, I use a Black Magic Probe Mini V2.1 with the native binary from the latest automated build:

![black_magic_gdb](https://user-images.githubusercontent.com/16087328/118496803-766b0c80-b6f2-11eb-8fe1-bca1df549b80.PNG)

Has you can see, when I try to load the program, the loading failed. The board use a LPC802M001JDH20 and I know that SWD flashing on LPC is a little bit tricky ( https://github.com/blacksphere/blackmagic/wiki/Adding-target-drivers ) but I can see that this chip is supposed to be supported in lpc11xx.c. Here's my setup:

![PXL_20210517_132219121](https://user-images.githubusercontent.com/16087328/118498209-c6969e80-b6f3-11eb-85a3-28cccca285e2.jpg)

I also have the jumper to enable SWD:

![PXL_20210517_132249595](https://user-images.githubusercontent.com/16087328/118498319-e75ef400-b6f3-11eb-940d-639be7db28e0.jpg)

the schematics for the board can be found here: https://www.nxp.com/products/processors-and-microcontrollers/arm-microcontrollers/general-purpose-mcus/lpc800-cortex-m0-plus-/lpcxpresso802-for-the-lpc802-family-of-mcus:OM40000

**Comment by UweBonnes** [comment]
Untils some point in time, wild probing for devices was done, with the danger of hangup. Now a more educated guess is made and the guess did not know about the LPC8(0)? I just added  probing for  lpc11 when a M0+ is detected. I just pushed a fix as https://github.com/UweBonnes/blackmagic/tree/fixes and will soon make it #885. Can you test?

**Comment by 0x72D0** [comment]
Thanks for your quick response, I tried the fix you sent. It did succeed to correctly detect the chip this time, but unfortunately the chip still fail to load new code:

![image](https://user-images.githubusercontent.com/16087328/118527485-58f86b80-b70f-11eb-907c-78d456d0d0b2.png)

**Comment by 0x72D0** [comment]
Thanks for your quick response, I tried the fix you sent. The fix seem to succeed, but now I have a new error message while trying to load the code:

![image](https://user-images.githubusercontent.com/16087328/118528046-e50a9300-b70f-11eb-9904-52f9b86a3a96.png)

**Comment by UweBonnes** [comment]
You must first attach before flashing "load"

**Comment by 0x72D0** [comment]
yeah I forgot to load the first time, but in when I attach to my device I still receive the following error:

![image](https://user-images.githubusercontent.com/16087328/118536899-49325480-b71a-11eb-9b91-e7b3b9cfa0b8.png)

**Comment by UweBonnes** [comment]
Does the LPC80x have flash protection? Is it set? Can try to flash in some other way?

**Comment by 0x72D0** [comment]
I succeed to upload it by removing the ext dbg jumper and by uploading my code in USB with MCUxpresso.

**Comment by UweBonnes** [comment]
If it is a OM4000 board, it has a built-in CMSIS-DAP. BMP/hosted should recognize the CMSIS-DAP and it should be useable with pyocd and OpenOcd too.

**Comment by 0x72D0** [comment]
To test with OpenOcd I use the same bmp with the same configuration from when I tried to flash using the SWD interface. I've mounted my bmp in an Ubuntu VM as ttyACM0.

It's my first time using OpenOcd, so I don't know if I did it wrong, but it give me the following results:

![image](https://user-images.githubusercontent.com/16087328/118671626-a3d4ba80-b7c5-11eb-90fd-bbfcc39f6281.png)

**Comment by UweBonnes** [comment]
OpenOCD does not handle the BMP dongle.. Unplug the BMP dongle and switch to the built-in CMSIS DAP adapter. Try again with the OpenOCD test above, Try also PyOCD. And BMP/hosted "make PROBE_HOST=hosted", can handle CMSIS DAP too. Compile with "make PROBE_HOST=hosted"

**Comment by 0x72D0** [comment]
I still have the error with OpenOCD while the hosted blackmagic is running (I've disconnected the dongle and I've removed the ext dbg jumper this time):

![image](https://user-images.githubusercontent.com/16087328/118682355-5d378e00-b7ce-11eb-832b-e62fa21d3208.png)

I'm pretty sure the board is detected as ttyACM0, dmesg give me the following output:

![Capture](https://user-images.githubusercontent.com/16087328/118682708-b0114580-b7ce-11eb-9dd8-8a1d73d62a47.PNG)

I'm gonna try to test with pyOCD soon.

**Comment by UweBonnes** [comment]
blackmagic -t should find the device and blackmagic -h to learn abouy the verbosity levels.

**Comment by 0x72D0** [comment]
blackmagic -t -v 31 give me the following output:

```INFO: Open USB 80ee:0021 class  0 failed
BMP hosted v1.6.1-790-gb1325be
 for ST-Link V2/3, CMSIS_DAP, JLINK and LIBFTDI/MPSSE
Using 1fc9:0132 09028035 NXP Semiconductors
 LPC11U3x CMSIS-DAP v1.0.4
Blacklist
cmd :   00.03.
cmd res:03.00.
cmd :   00.00.04.
cmd res:00.05.31.2e.31.30.00.00.00.00.00.00.00.00.00.00.
Ver 1.10, cmd :   00.00.f0.
cmd res:00.01.11.00.00.00.00.00.00.00.00.00.00.00.00.00.
Cap (0x11): SWD, Atomic Cmds
Running in Test Mode
Target voltage: (null) Volt
cmd :   00.11.00.09.3d.00.
cmd res:11.00.00.00.00.00.
Speed set to  4.0000 MHz for SWD
cmd :   00.04.02.80.00.80.00.
cmd res:04.00.00.00.00.00.00.
cmd :   00.13.00.
cmd res:13.00.00.
cmd :   00.02.01.
cmd res:02.01.00.
cmd :   00.01.00.01.
cmd res:01.00.00.00.
cmd :   00.12.88.ff.ff.ff.ff.ff.ff.ff.9e.e7.ff.ff.ff.ff.ff.ff.ff.00.
cmd res:12.00.00.00.00.00.00.00.00.00.00.00.00.00.00.00.
cmd :   00.05.00.01.02.
cmd res:05.01.01.77.14.c1.0b.00.00.00.00.00.00.00.00.00.
cmd :   00.12.20.ff.ff.ff.ff.
cmd res:12.00.
cmd :   00.12.20.ff.ff.ff.ff.
cmd res:12.00.
cmd :   00.12.20.92.f3.09.62.
cmd res:12.00.
cmd :   00.12.20.95.2d.85.86.
cmd res:12.00.
cmd :   00.12.20.e9.af.dd.e3.
cmd res:12.00.
cmd :   00.12.20.a2.0e.bc.19.
cmd res:12.00.
cmd :   00.12.0c.a0.01.00.00.
cmd res:12.00.
cmd :   00.12.20.ff.ff.ff.ff.
cmd res:12.00.
cmd :   00.12.20.ff.ff.ff.0f.
cmd res:12.00.
cmd :   00.05.00.01.02.
cmd res:05.01.01.77.14.c1.0b.00.00.
	dap_read_reg 00 0bc11477
DPIDR 0x0bc11477 (v1 MINDP rev0)
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
Write CTRL/STAT: 0xf0000040
	dap_write_reg 04 f0000040
cmd :   00.05.00.01.04.40.00.00.f0.
cmd res:05.01.01.00.00.00.00.00.00.
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
Write CTRL/STAT: 0xf4000040
	dap_write_reg 04 f4000040
cmd :   00.05.00.01.04.40.00.00.f4.
cmd res:05.01.01.00.00.00.00.00.00.
Write CTRL/STAT: 0xf0000040
	dap_write_reg 04 f0000040
cmd :   00.05.00.01.04.40.00.00.f0.
cmd res:05.01.01.00.00.00.00.00.00.
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
dp_read 0004 f0000040
Read  CTRL/STAT: 0xf0000040
RESET_SEQ failed
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.00.0f.
cmd res:05.02.01.31.00.77.04.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 IDR   : 0x04770031
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.00.0b.
cmd res:05.02.01.03.f0.0f.e0.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 BASE  : 0xe00ff003
dap_ap_read_start
cmd :   00.05.00.02.08.00.00.00.00.03.
cmd res:05.02.01.52.00.00.03.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 CSW   : 0x03000052
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.00.07.
cmd res:05.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 CFG   : 0x00000000
AP   0: IDR=04770031 CFG=00000000 BASE=e00ff003 CSW=03000040 (AHB-AP var3 rev0
ap_mem_write_sized @ e000edf0 len 4, align 4: 03 00 5f a0
memwrite @ e000edf0 len 4, align 2 , a05f0003 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f0.ed.00.e0.0d.03.00.5f.a0.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
memread @ e000edf0 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f0.ed.00.e0.0f.
cmd res:05.04.01.03.00.03.01.00.00.00.00.00.00.00.00.00.
ap_memread @ e000edf0 len 4: 03 00 03 01
Halt via DHCSR: success 01030003 after 11ms
memread @ e000edfc len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.fc.ed.00.e0.0f.
cmd res:05.04.01.00.00.00.01.00.00.00.00.00.00.00.00.00.
ap_memread @ e000edfc len 4: 00 00 00 01
ap_mem_write_sized @ e000edfc len 4, align 4: 01 04 00 01
memwrite @ e000edfc len 4, align 2 , 01000401 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.fc.ed.00.e0.0d.01.04.00.01.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
memread @ e000edf0 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f0.ed.00.e0.0f.
cmd res:05.04.01.03.00.03.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e000edf0 len 4: 03 00 03 00
memread @ e00ffff0 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f0.ff.0f.e0.0f.
cmd res:05.04.01.0d.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e00ffff0 len 4: 0d 00 00 00
memread @ e00ffff4 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f4.ff.0f.e0.0f.
cmd res:05.04.01.10.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e00ffff4 len 4: 10 00 00 00
memread @ e00ffff8 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f8.ff.0f.e0.0f.
cmd res:05.04.01.05.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e00ffff8 len 4: 05 00 00 00
memread @ e00ffffc len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.fc.ff.0f.e0.0f.
cmd res:05.04.01.b1.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e00ffffc len 4: b1 00 00 00
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
	dap_write_reg 00 00000000
cmd :   00.05.00.01.00.00.00.00.00.
cmd res:05.01.01.00.00.00.00.00.00.
DP Error 0x00000000
memread @ e00fffd0 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.d0.ff.0f.e0.0f.
cmd res:05.04.01.04.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e00fffd0 len 4: 04 00 00 00
memread @ e00fffd4 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.d4.ff.0f.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e00fffd4 len 4: 00 00 00 00
memread @ e00fffd8 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.d8.ff.0f.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e00fffd8 len 4: 00 00 00 00
memread @ e00fffdc len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.dc.ff.0f.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e00fffdc len 4: 00 00 00 00
memread @ e00fffe0 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.e0.ff.0f.e0.0f.
cmd res:05.04.01.c0.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e00fffe0 len 4: c0 00 00 00
memread @ e00fffe4 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.e4.ff.0f.e0.0f.
cmd res:05.04.01.b4.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e00fffe4 len 4: b4 00 00 00
memread @ e00fffe8 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.e8.ff.0f.e0.0f.
cmd res:05.04.01.0b.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e00fffe8 len 4: 0b 00 00 00
memread @ e00fffec len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.ec.ff.0f.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e00fffec len 4: 00 00 00 00
memread @ e00fffcc len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.cc.ff.0f.e0.0f.
cmd res:05.04.01.01.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e00fffcc len 4: 01 00 00 00
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
	dap_write_reg 00 00000000
cmd :   00.05.00.01.00.00.00.00.00.
cmd res:05.01.01.00.00.00.00.00.00.
DP Error 0x00000000
ROM: Table BASE=0xe00ff000 SYSMEM=0x00000001, designer 43b Partno 4c0
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
	dap_write_reg 00 00000000
cmd :   00.05.00.01.00.00.00.00.00.
cmd res:05.01.01.00.00.00.00.00.00.
DP Error 0x00000000
memread @ e00ff000 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.00.f0.0f.e0.0f.
cmd res:05.04.01.03.f0.f0.ff.00.00.00.00.00.00.00.00.00.
ap_memread @ e00ff000 len 4: 03 f0 f0 ff
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
	dap_write_reg 00 00000000
cmd :   00.05.00.01.00.00.00.00.00.
cmd res:05.01.01.00.00.00.00.00.00.
DP Error 0x00000000
memread @ e000eff0 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f0.ef.00.e0.0f.
cmd res:05.04.01.0d.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e000eff0 len 4: 0d 00 00 00
memread @ e000eff4 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f4.ef.00.e0.0f.
cmd res:05.04.01.e0.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e000eff4 len 4: e0 00 00 00
memread @ e000eff8 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f8.ef.00.e0.0f.
cmd res:05.04.01.05.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e000eff8 len 4: 05 00 00 00
memread @ e000effc len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.fc.ef.00.e0.0f.
cmd res:05.04.01.b1.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e000effc len 4: b1 00 00 00
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
	dap_write_reg 00 00000000
cmd :   00.05.00.01.00.00.00.00.00.
cmd res:05.01.01.00.00.00.00.00.00.
DP Error 0x00000000
memread @ e000efd0 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.d0.ef.00.e0.0f.
cmd res:05.04.01.04.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e000efd0 len 4: 04 00 00 00
memread @ e000efd4 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.d4.ef.00.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e000efd4 len 4: 00 00 00 00
memread @ e000efd8 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.d8.ef.00.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e000efd8 len 4: 00 00 00 00
memread @ e000efdc len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.dc.ef.00.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e000efdc len 4: 00 00 00 00
memread @ e000efe0 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.e0.ef.00.e0.0f.
cmd res:05.04.01.08.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e000efe0 len 4: 08 00 00 00
memread @ e000efe4 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.e4.ef.00.e0.0f.
cmd res:05.04.01.b0.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e000efe4 len 4: b0 00 00 00
memread @ e000efe8 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.e8.ef.00.e0.0f.
cmd res:05.04.01.0b.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e000efe8 len 4: 0b 00 00 00
memread @ e000efec len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.ec.ef.00.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e000efec len 4: 00 00 00 00
0 0xe000e000: Generic IP component - Cortex-M0 SCS (System Control Space) (PIDR = 0x04000bb008  DEVTYPE = 0x00 ARCHID = 0x0000)-> cortexm_probe
memread @ e000ed00 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.00.ed.00.e0.0f.
cmd res:05.04.01.01.c6.0c.41.00.00.00.00.00.00.00.00.00.
ap_memread @ e000ed00 len 4: 01 c6 0c 41
CPUID 0x410cc601 (M0+ var 0 rev 1)
memread @ e000ed88 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.88.ed.00.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e000ed88 len 4: 00 00 00 00
ap_mem_write_sized @ e000ed88 len 4, align 4: 00 00 f0 00
memwrite @ e000ed88 len 4, align 2 , 00f00000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.88.ed.00.e0.0d.00.00.f0.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
memread @ e000ed88 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.88.ed.00.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e000ed88 len 4: 00 00 00 00
memread @ e000ed7c len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.7c.ed.00.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e000ed7c len 4: 00 00 00 00
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
	dap_write_reg 00 00000000
cmd :   00.05.00.01.00.00.00.00.00.
cmd res:05.01.01.00.00.00.00.00.00.
DP Error 0x00000000
memread @ 400483f4 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f4.83.04.40.0f.
cmd res:05.04.01.2b.10.02.18.00.00.00.00.00.00.00.00.00.
ap_memread @ 400483f4 len 4: 2b 10 02 18
LPC11xx: Unknown IDCODE 0x1802102b
memread @ 400483f8 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f8.83.04.40.0f.
cmd res:05.04.01.21.80.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ 400483f8 len 4: 21 80 00 00
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
	dap_write_reg 00 00000000
cmd :   00.05.00.01.00.00.00.00.00.
cmd res:05.01.01.00.00.00.00.00.00.
DP Error 0x00000000
memread @ e00ff004 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.04.f0.0f.e0.0f.
cmd res:05.04.01.03.20.f0.ff.00.00.00.00.00.00.00.00.00.
ap_memread @ e00ff004 len 4: 03 20 f0 ff
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
	dap_write_reg 00 00000000
cmd :   00.05.00.01.00.00.00.00.00.
cmd res:05.01.01.00.00.00.00.00.00.
DP Error 0x00000000
memread @ e0001ff0 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f0.1f.00.e0.0f.
cmd res:05.04.01.0d.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0001ff0 len 4: 0d 00 00 00
memread @ e0001ff4 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f4.1f.00.e0.0f.
cmd res:05.04.01.e0.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0001ff4 len 4: e0 00 00 00
memread @ e0001ff8 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f8.1f.00.e0.0f.
cmd res:05.04.01.05.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0001ff8 len 4: 05 00 00 00
memread @ e0001ffc len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.fc.1f.00.e0.0f.
cmd res:05.04.01.b1.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0001ffc len 4: b1 00 00 00
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
	dap_write_reg 00 00000000
cmd :   00.05.00.01.00.00.00.00.00.
cmd res:05.01.01.00.00.00.00.00.00.
DP Error 0x00000000
memread @ e0001fd0 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.d0.1f.00.e0.0f.
cmd res:05.04.01.04.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0001fd0 len 4: 04 00 00 00
memread @ e0001fd4 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.d4.1f.00.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0001fd4 len 4: 00 00 00 00
memread @ e0001fd8 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.d8.1f.00.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0001fd8 len 4: 00 00 00 00
memread @ e0001fdc len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.dc.1f.00.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0001fdc len 4: 00 00 00 00
memread @ e0001fe0 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.e0.1f.00.e0.0f.
cmd res:05.04.01.0a.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0001fe0 len 4: 0a 00 00 00
memread @ e0001fe4 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.e4.1f.00.e0.0f.
cmd res:05.04.01.b0.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0001fe4 len 4: b0 00 00 00
memread @ e0001fe8 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.e8.1f.00.e0.0f.
cmd res:05.04.01.0b.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0001fe8 len 4: 0b 00 00 00
memread @ e0001fec len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.ec.1f.00.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0001fec len 4: 00 00 00 00
1 0xe0001000: Generic IP component - Cortex-M0 DWT (Data Watchpoint and Trace) (PIDR = 0x04000bb00a  DEVTYPE = 0x00 ARCHID = 0x0000)
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
	dap_write_reg 00 00000000
cmd :   00.05.00.01.00.00.00.00.00.
cmd res:05.01.01.00.00.00.00.00.00.
DP Error 0x00000000
memread @ e00ff008 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.08.f0.0f.e0.0f.
cmd res:05.04.01.03.30.f0.ff.00.00.00.00.00.00.00.00.00.
ap_memread @ e00ff008 len 4: 03 30 f0 ff
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
	dap_write_reg 00 00000000
cmd :   00.05.00.01.00.00.00.00.00.
cmd res:05.01.01.00.00.00.00.00.00.
DP Error 0x00000000
memread @ e0002ff0 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f0.2f.00.e0.0f.
cmd res:05.04.01.0d.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0002ff0 len 4: 0d 00 00 00
memread @ e0002ff4 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f4.2f.00.e0.0f.
cmd res:05.04.01.e0.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0002ff4 len 4: e0 00 00 00
memread @ e0002ff8 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f8.2f.00.e0.0f.
cmd res:05.04.01.05.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0002ff8 len 4: 05 00 00 00
memread @ e0002ffc len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.fc.2f.00.e0.0f.
cmd res:05.04.01.b1.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0002ffc len 4: b1 00 00 00
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
	dap_write_reg 00 00000000
cmd :   00.05.00.01.00.00.00.00.00.
cmd res:05.01.01.00.00.00.00.00.00.
DP Error 0x00000000
memread @ e0002fd0 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.d0.2f.00.e0.0f.
cmd res:05.04.01.04.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0002fd0 len 4: 04 00 00 00
memread @ e0002fd4 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.d4.2f.00.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0002fd4 len 4: 00 00 00 00
memread @ e0002fd8 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.d8.2f.00.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0002fd8 len 4: 00 00 00 00
memread @ e0002fdc len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.dc.2f.00.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0002fdc len 4: 00 00 00 00
memread @ e0002fe0 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.e0.2f.00.e0.0f.
cmd res:05.04.01.0b.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0002fe0 len 4: 0b 00 00 00
memread @ e0002fe4 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.e4.2f.00.e0.0f.
cmd res:05.04.01.b0.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0002fe4 len 4: b0 00 00 00
memread @ e0002fe8 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.e8.2f.00.e0.0f.
cmd res:05.04.01.0b.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0002fe8 len 4: 0b 00 00 00
memread @ e0002fec len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.ec.2f.00.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0002fec len 4: 00 00 00 00
2 0xe0002000: Generic IP component - Cortex-M0 BPU (Breakpoint Unit) (PIDR = 0x04000bb00b  DEVTYPE = 0x00 ARCHID = 0x0000)
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
	dap_write_reg 00 00000000
cmd :   00.05.00.01.00.00.00.00.00.
cmd res:05.01.01.00.00.00.00.00.00.
DP Error 0x00000000
memread @ e00ff00c len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.0c.f0.0f.e0.0f.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e00ff00c len 4: 00 00 00 00
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
	dap_write_reg 00 00000000
cmd :   00.05.00.01.00.00.00.00.00.
cmd res:05.01.01.00.00.00.00.00.00.
DP Error 0x00000000
ROM: Table END
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.01.0f.
cmd res:05.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 IDR   : 0x00000000
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.01.0b.
cmd res:05.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 BASE  : 0x00000000
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.02.0f.
cmd res:05.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 IDR   : 0x00000000
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.02.0b.
cmd res:05.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 BASE  : 0x00000000
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.03.0f.
cmd res:05.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 IDR   : 0x00000000
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.03.0b.
cmd res:05.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 BASE  : 0x00000000
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.04.0f.
cmd res:05.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 IDR   : 0x00000000
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.04.0b.
cmd res:05.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 BASE  : 0x00000000
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.05.0f.
cmd res:05.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 IDR   : 0x00000000
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.05.0b.
cmd res:05.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 BASE  : 0x00000000
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.06.0f.
cmd res:05.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 IDR   : 0x00000000
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.06.0b.
cmd res:05.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 BASE  : 0x00000000
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.07.0f.
cmd res:05.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 IDR   : 0x00000000
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.07.0b.
cmd res:05.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 BASE  : 0x00000000
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.08.0f.
cmd res:05.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 IDR   : 0x00000000
dap_ap_read_start
cmd :   00.05.00.02.08.f0.00.00.08.0b.
cmd res:05.02.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
Read  AP 0x01 BASE  : 0x00000000
ap_mem_write_sized @ e000edf0 len 4, align 4: 01 00 5f a0
memwrite @ e000edf0 len 4, align 2 , a05f0001 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f0.ed.00.e0.0d.01.00.5f.a0.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
***  1      LPC802 M0+
cmd :   00.05.00.01.06.
cmd res:05.01.01.40.00.00.f0.00.00.
	dap_read_reg 04 f0000040
	dap_write_reg 00 00000000
cmd :   00.05.00.01.00.00.00.00.00.
cmd res:05.01.01.00.00.00.00.00.00.
DP Error 0x00000000
ap_mem_write_sized @ e000edf0 len 4, align 4: 03 00 5f a0
memwrite @ e000edf0 len 4, align 2 , a05f0003 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f0.ed.00.e0.0d.03.00.5f.a0.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e000edfc len 4, align 4: 01 04 00 01
memwrite @ e000edfc len 4, align 2 , 01000401 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.fc.ed.00.e0.0d.01.04.00.01.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e000ed30 len 4, align 4: 1f 00 00 00
memwrite @ e000ed30 len 4, align 2 , 0000001f start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.30.ed.00.e0.0d.1f.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
memread @ e0002000 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.00.20.00.e0.0f.
cmd res:05.04.01.41.00.00.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e0002000 len 4: 41 00 00 00
memread @ e0001000 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.00.10.00.e0.0f.
cmd res:05.04.01.00.00.00.20.00.00.00.00.00.00.00.00.00.
ap_memread @ e0001000 len 4: 00 00 00 20
ap_mem_write_sized @ e0002008 len 4, align 4: 00 00 00 00
memwrite @ e0002008 len 4, align 2 , 00000000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.08.20.00.e0.0d.00.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e000200c len 4, align 4: 00 00 00 00
memwrite @ e000200c len 4, align 2 , 00000000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.0c.20.00.e0.0d.00.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e0002010 len 4, align 4: 00 00 00 00
memwrite @ e0002010 len 4, align 2 , 00000000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.10.20.00.e0.0d.00.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e0002014 len 4, align 4: 00 00 00 00
memwrite @ e0002014 len 4, align 2 , 00000000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.14.20.00.e0.0d.00.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e0001028 len 4, align 4: 00 00 00 00
memwrite @ e0001028 len 4, align 2 , 00000000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.28.10.00.e0.0d.00.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e0001038 len 4, align 4: 00 00 00 00
memwrite @ e0001038 len 4, align 2 , 00000000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.38.10.00.e0.0d.00.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e0001048 len 4, align 4: 00 00 00 00
memwrite @ e0001048 len 4, align 2 , 00000000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.48.10.00.e0.0d.00.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e0001058 len 4, align 4: 00 00 00 00
memwrite @ e0001058 len 4, align 2 , 00000000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.58.10.00.e0.0d.00.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e0002000 len 4, align 4: 03 00 00 00
memwrite @ e0002000 len 4, align 2 , 00000003 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.00.20.00.e0.0d.03.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
memread @ e000edf0 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f0.ed.00.e0.0f.
cmd res:05.04.01.03.00.03.01.00.00.00.00.00.00.00.00.00.
ap_memread @ e000edf0 len 4: 03 00 03 01
memread @ e000edf0 len 4, align 2 , start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f0.ed.00.e0.0f.
cmd res:05.04.01.03.00.03.00.00.00.00.00.00.00.00.00.00.
ap_memread @ e000edf0 len 4: 03 00 03 00
RAM   Start: 0x10000000 length = 0x800
Flash Start: 0x00000000 length = 0x4000 blocksize 0x400
ap_mem_write_sized @ e0002008 len 4, align 4: 00 00 00 00
memwrite @ e0002008 len 4, align 2 , 00000000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.08.20.00.e0.0d.00.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e000200c len 4, align 4: 00 00 00 00
memwrite @ e000200c len 4, align 2 , 00000000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.0c.20.00.e0.0d.00.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e0002010 len 4, align 4: 00 00 00 00
memwrite @ e0002010 len 4, align 2 , 00000000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.10.20.00.e0.0d.00.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e0002014 len 4, align 4: 00 00 00 00
memwrite @ e0002014 len 4, align 2 , 00000000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.14.20.00.e0.0d.00.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e0001028 len 4, align 4: 00 00 00 00
memwrite @ e0001028 len 4, align 2 , 00000000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.28.10.00.e0.0d.00.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e0001038 len 4, align 4: 00 00 00 00
memwrite @ e0001038 len 4, align 2 , 00000000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.38.10.00.e0.0d.00.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e0001048 len 4, align 4: 00 00 00 00
memwrite @ e0001048 len 4, align 2 , 00000000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.48.10.00.e0.0d.00.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e0001058 len 4, align 4: 00 00 00 00
memwrite @ e0001058 len 4, align 2 , 00000000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.58.10.00.e0.0d.00.00.00.00.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e000edfc len 4, align 4: 00 00 00 01
memwrite @ e000edfc len 4, align 2 , 01000000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.fc.ed.00.e0.0d.00.00.00.01.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
ap_mem_write_sized @ e000edf0 len 4, align 4: 00 00 5f a0
memwrite @ e000edf0 len 4, align 2 , a05f0000 start: 
cmd :   00.05.00.04.08.00.00.00.00.01.52.00.00.03.05.f0.ed.00.e0.0d.00.00.5f.a0.
cmd res:05.04.01.00.00.00.00.00.00.00.00.00.00.00.00.00.
cmd :   00.03.
cmd res:03.00.
```

**Comment by UweBonnes** [comment]
-v31 is very noisy. "-t" impies "-v3" and should detect the device. "blachmagic <file.bin>" would try to flash the binary at 0. Or start the gdb server only "blackmagic" and cionnect gdb to "tar ext :2000"

**Comment by UweBonnes** [comment]
I will get a OM40000UL soon...

**Comment by 0x72D0** [comment]
Ok I think I understand better, so I ran blackmagic -v 3 and try to connect to it with gdb-multiarch, it succeed to detect the LPC802 correctly, but the loading still fail with the same error:

![image](https://user-images.githubusercontent.com/16087328/118691469-1c904280-b7d7-11eb-8504-eb2a23bc0778.png)

the hosted blackmagic output is the following:

![image](https://user-images.githubusercontent.com/16087328/118691663-4ba6b400-b7d7-11eb-93f1-00ab1e060512.png)

I'm gonna try with pyOCD soon

**Comment by 0x72D0** [comment]
Same problem on pyOCD:

![image](https://user-images.githubusercontent.com/16087328/118692805-6f1e2e80-b7d8-11eb-9f03-69ab2f81bdbc.png)

**Comment by 0x72D0** [comment]
with pyOCD I still have a failure on the loading:

![image](https://user-images.githubusercontent.com/16087328/118694276-e99b7e00-b7d9-11eb-83e6-74e7def70682.png)

**Comment by UweBonnes** [comment]
So there is something more to understand that neither pyocd and bmp knows yet. What gdb server does MCUxpresso use?

**Comment by 0x72D0** [comment]
The one I use to successfully upload my code on the OM40000 dosen't seem to be a gdb server, it's called the LinkServer Debugger.

**Comment by 0x72D0** [comment]
Did someone succeed to upload on a LPC802 chip before( without being on the OM40000 )? I'm more trying to see if I can upload on a similar chip before the real board with an onboard Jtag interface arrive.

**Comment by UweBonnes** [comment]
#835

**Comment by 0x72D0** [comment]
Thanks :)

**Comment by 0x72D0** [comment]
I just succeed flashing the chip via SWD using the LPC-LINK 2 and the LinkServer on MCUxpresso.

**Comment by UweBonnes** [comment]
I can read the flash content of the OM40000 board to a bin file. Trying to reprogram (erase, flash) with BMP/CMSIS only erases and than steps into error. Flash is erase. BMP/BMP_HOSTED hangs in the last chunk. However repowering bring up the board and compare succeeds.

**Comment by esden** [comment]
Considering that we have a report that it was possible to program that host board and the target. I am assuming this issue is resolved, so I am closing it. Thank you everyone. :) 

If there is still a problem here that needs to be addressed please feel free to reopen this issue.
